### ISSUE TITLE
[ADDITIONAL SOURCE] Terraform Provider for SAP BTP

### ISSUE THREAD

**Issue by lechnerc77** [htammen/saptodon-sap-version-bot#1]
Hi @htammen thanks for this initiative! Would it be possible to add the *Terraform Provider for SAP BTP* to the list of watched projects?

Here some information about the project:

- The project is located on GitHub: <https://github.com/SAP/terraform-provider-btp>
- Releases are published via GitHub releases: <https://github.com/SAP/terraform-provider-btp/releases>
- The project is published as open source following the [Apache-2.0](https://github.com/SAP/terraform-provider-btp?tab=Apache-2.0-1-ov-file#readme) license

**Comment by htammen** [comment]
Hi @lechnerc77 done
![Screenshot_20240220-060540.jpg](https://github.com/htammen/saptodon-sap-version-bot/assets/847143/f6b28840-edb1-42bd-8aeb-ee67ae8d4c33)

**Comment by lechnerc77** [comment]
@htammen great - thanks a lot!
